# Auto-generated by Codex agent on 2025-12-01T01:04:00Z
import copy
import json
from pathlib import Path

import pytest

POLICY_PATH = Path("config") / "autoselect_policy.json"


def _load_policy():
    if not POLICY_PATH.exists():
        pytest.skip(f"Missing policy file at {POLICY_PATH}")
    with POLICY_PATH.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def _choose_variant(policy: dict, free_gb: float):
    if policy.get("force_variant"):
        return policy["force_variant"], "force_variant"

    rules = sorted(policy.get("rules", []), key=lambda r: r.get("min_free_gb", -1), reverse=True)
    for rule in rules:
        if free_gb >= rule.get("min_free_gb", -1):
            return rule.get("variant"), rule.get("reason")

    variants = policy.get("variants", [])
    if variants:
        return variants[-1], "fallback:last_variant"
    return None, None


def test_policy_allows_default_variants():
    policy = _load_policy()
    variants = set(policy.get("variants", []))
    assert variants, "Policy variants must not be empty"
    force_variant = policy.get("force_variant")
    if force_variant:
        assert force_variant in variants


@pytest.mark.parametrize(
    "free_gb,expected_variant",
    [
        (2.0, "q4_K_M"),
        (4.0, "q8_0"),
        (12.5, "q8_0"),
    ],
)
def test_rule_selection_matches_policy(free_gb, expected_variant):
    policy = _load_policy()
    variant, reason = _choose_variant(policy, free_gb)
    assert variant == expected_variant
    assert reason
    assert variant in policy["variants"]


def test_force_variant_overrides_rules():
    policy = copy.deepcopy(_load_policy())
    policy["force_variant"] = "q4_0"
    variant, reason = _choose_variant(policy, 10.0)
    assert variant == "q4_0"
    assert reason == "force_variant"
